name: newmaster
description: A new Flutter project.

publish_to: 'none' # Set to 'none' to avoid publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0' # Ensure this matches your Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_gauges: 21.2.4
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  file_picker: ^5.2.2
  image_picker: ^0.8.6
  intl: ^0.17.0
  image: ^3.2.2
  hydrated_bloc: ^9.0.0
  path_provider: ^2.1.3
  adaptive_theme: ^3.4.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  fl_chart: ^0.68.0
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^12.1.1
  dartx: ^1.2.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.0
  auto_size_widget: ^0.0.4
  flutter_echarts: ^2.5.0
  charts_flutter: ^0.12.0
  excel: ^2.0.5
  csv: ^6.0.0
  table_calendar: ^3.0.3
  html: ^0.15.0
  http: ^1.2.1
  lcd_number_text: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
